#!/data/data/com.dsharnessmobile.shell/files/usr/bin/bash
#
# Builds StrongholdProtocol.apk without Gradle.
#
#   aapt2 compile -> aapt2 link --output-to-dir -> javac -> d8 -> make_apk.py -> apksigner
#
# make_apk.py replaces `zipalign` (not packaged in Termux); see its header for why that matters.
#
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
export PATH="/data/data/com.dsharnessmobile.shell/files/usr/bin:$PATH"

ANDROID_JAR="${ANDROID_JAR:-$HERE/sdkroot/android-35/android.jar}"
SRC="$HERE/android"
OUT="$HERE/out"
MIN_SDK="${MIN_SDK:-21}"
TARGET_SDK="${TARGET_SDK:-34}"
VERSION_CODE=1
VERSION_NAME="4.1"

KEYSTORE="$HERE/keys/stronghold.keystore"
KS_PASS="stronghold"
KS_ALIAS="stronghold"

[ -f "$ANDROID_JAR" ] || { echo "缺少 android.jar: $ANDROID_JAR" >&2; exit 1; }

echo "==> 清理"
rm -rf "$OUT"
mkdir -p "$OUT/compiled" "$OUT/gen" "$OUT/classes" "$OUT/dex" "$OUT/contents"

echo "==> 1/6 编译资源 (aapt2 compile)"
aapt2 compile --dir "$SRC/res" -o "$OUT/compiled/res.zip"

echo "==> 2/6 链接资源与清单 (aapt2 link)"
aapt2 link \
    --output-to-dir -o "$OUT/contents" \
    -I "$ANDROID_JAR" \
    --manifest "$SRC/AndroidManifest.xml" \
    --java "$OUT/gen" \
    --min-sdk-version "$MIN_SDK" \
    --target-sdk-version "$TARGET_SDK" \
    --version-code "$VERSION_CODE" \
    --version-name "$VERSION_NAME" \
    "$OUT/compiled/res.zip"

echo "==> 3/6 编译 Java (javac)"
# 把版本号和构建时刻烧进包里：设置页会显示「v1.9 · 构建于 2026-10-06 20:15」，
# Release 标题也用同一个时间戳，这样版本多了以后时间线不会乱。
BUILT_AT="$(date '+%Y-%m-%d %H:%M')"
mkdir -p "$OUT/gen/com/strongholdprotocol/client"
printf 'package com.strongholdprotocol.client;\n\n/** Generated by build.sh -- do not edit. */\nfinal class BuildStamp {\n    static final String VERSION = "%s";\n    static final String BUILT_AT = "%s";\n    private BuildStamp() {}\n}\n' \
    "$VERSION_NAME" "$BUILT_AT" > "$OUT/gen/com/strongholdprotocol/client/BuildStamp.java"
echo "    版本 $VERSION_NAME · 构建于 $BUILT_AT"
find "$SRC/java" "$OUT/gen" -name '*.java' > "$OUT/sources.txt"
javac -nowarn --release 8 \
    -classpath "$ANDROID_JAR" \
    -d "$OUT/classes" \
    @"$OUT/sources.txt"

echo "==> 4/6 转 DEX (d8)"
jar cf "$OUT/classes.jar" -C "$OUT/classes" .
d8 --min-api "$MIN_SDK" --lib "$ANDROID_JAR" --output "$OUT/dex" "$OUT/classes.jar"
cp "$OUT/dex/classes.dex" "$OUT/contents/classes.dex"

echo "==> 5/6 打包并对齐 (make_apk.py)"
# android/assets/ is the pre-installed media payload; make_apk.py packs it under assets/ without
# copying it into the staging directory first.
# 随包字体：源码放在仓库里（OFL，约 240 KB），打包前复制进 assets/。
# 不能直接放在 android/assets/ 下——那个目录是构建产物，被 .gitignore 忽略，
# 放在那里会导致克隆后构建出的包静默缺少字体。
if [ -d "$HERE/localfonts" ]; then
    rm -rf "$SRC/assets/localfonts"
    mkdir -p "$SRC/assets"
    cp -r "$HERE/localfonts" "$SRC/assets/localfonts"
    echo "    随包字体: $(ls "$HERE/localfonts" | wc -l) 个文件, $(du -sh "$HERE/localfonts" | cut -f1)"
else
    echo "    ! localfonts/ 不存在，Google 字体请求将只返回空样式表（文字会回退到系统字体）" >&2
fi

ASSETS_ARG=""
[ -d "$SRC/assets" ] && ASSETS_ARG="$SRC/assets"
LIB_ARG=""
[ -d "$SRC/lib" ] && LIB_ARG="$SRC/lib"

if [ -n "$LIB_ARG" ]; then
    echo "    node 运行时: $(ls "$SRC/lib/arm64-v8a" | wc -l) 个 lib*.so, $(du -sh "$SRC/lib" | cut -f1)"
else
    echo "    ! android/lib 不存在，本机服务器将在运行时不可用" >&2
fi
if [ -n "$ASSETS_ARG" ]; then
    echo "    素材包: $(find "$SRC/assets/mirror" -type f 2>/dev/null | wc -l) 个文件, $(du -sh "$SRC/assets" | cut -f1)"
fi
python3 "$HERE/make_apk.py" "$OUT/contents" "$OUT/unsigned.apk" $ASSETS_ARG $LIB_ARG

echo "==> 6/6 签名 (apksigner)"
mkdir -p "$(dirname "$KEYSTORE")"
if [ ! -f "$KEYSTORE" ]; then
    echo "    生成自签名密钥库"
    keytool -genkeypair -v \
        -keystore "$KEYSTORE" -alias "$KS_ALIAS" \
        -keyalg RSA -keysize 2048 -validity 10950 \
        -storepass "$KS_PASS" -keypass "$KS_PASS" \
        -dname "CN=Stronghold Protocol Android, OU=Fan client, O=Non-commercial, C=CN" >/dev/null
fi

# Bound the signer's heap: it re-reads the whole archive (270+ MiB of assets) and the phone may not
# have 4 GiB to hand out.
JAVA_TOOL_OPTIONS="-Xmx2g" apksigner sign \
    --ks "$KEYSTORE" --ks-key-alias "$KS_ALIAS" \
    --ks-pass "pass:$KS_PASS" --key-pass "pass:$KS_PASS" \
    --min-sdk-version "$MIN_SDK" \
    --out "$HERE/StrongholdProtocol-$VERSION_NAME.apk" \
    "$OUT/unsigned.apk"

echo
echo "==> 校验"
apksigner verify --verbose --print-certs "$HERE/StrongholdProtocol-$VERSION_NAME.apk" | head -20
ls -la "$HERE/StrongholdProtocol-$VERSION_NAME.apk"
echo "完成: $HERE/StrongholdProtocol-$VERSION_NAME.apk"
